# Generated by Django 3.2.6 on 2021-09-09 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20210909_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='description',
        ),
    ]
