# Generated by Django 3.2.6 on 2021-09-10 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_auto_20210910_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tour',
        ),
    ]
