# Generated by Django 3.2.6 on 2021-09-12 09:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_remove_comment_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='note',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
