# Generated by Django 3.2.6 on 2021-12-22 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_auto_20211222_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='tags',
        ),
        migrations.AddField(
            model_name='tour',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.tag'),
        ),
    ]
