# Generated by Django 3.2.6 on 2021-12-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_auto_20211222_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='address',
        ),
    ]
