# Generated by Django 3.2.6 on 2021-12-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_remove_tour_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(default=None, upload_to='staffs/%Y/%m'),
        ),
    ]
